services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: webchatdb
      POSTGRES_USER: ${db_username}
      POSTGRES_PASSWORD: ${db_password}
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ./dbscripts:/docker-entrypoint-initdb.d
      - webchatdb-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  webchat:
    image: webchat_image
    container_name: webchat_container
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgres
volumes:
  webchatdb-data: